### ISSUE TITLE
Error for write_pdb function

### ISSUE THREAD

**Issue by thangnq1003** [Lemkul-Lab/cgenff_charmm2gmx#3]
I have run the newest version of cgenff_charmm2gmx_py3_nx2.py and get error:
$python3 cgenff_charmm2gmx_py3_nx2.py LIG lig_1.mol2 lig_1.str charmm36-jul2022.ff/
NOTE 1: Code tested with Python 3.5.2 and 3.7.3. Your version: 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:54:18)
[GCC 7.3.0]

NOTE 2: Code tested with NetworkX 2.3. Your version: 2.3

NOTE 3: Please be sure to use the same version of CGenFF in your simulations that was used during parameter generation:
--Version of CGenFF detected in  lig_1.str : 4.6
--Version of CGenFF detected in  charmm36-jul2022.ff//forcefield.doc : 4.6

NOTE 4: To avoid duplicated parameters, do NOT select the 'Include parameters that are already in CGenFF' option when uploading a molecule into CGenFF.

NOTE 5: 1 lone pairs found in topology that are not in the mol2 file. This is not a problem, just FYI!

Traceback (most recent call last):
  File "cgenff_charmm2gmx_py3_nx2.py", line 1050, in <module>
    m.write_pdb(f)
  File "cgenff_charmm2gmx_py3_nx2.py", line 983, in write_pdb
    ("ATOM",atomi+1,self.G.node[atomi]['name'],name,self.G.node[atomi]['resid'],resid,self.coord[atomi][0],
NameError: name 'name' is not defined

But when I have used the older version that worked well!

**Comment by hariseldon99** [comment]
I confirm the same error. I forked the repo and fixed it there:

[https://github.com/hariseldon99/cgenff_charmm2gmx](https://github.com/hariseldon99/cgenff_charmm2gmx
)

Until the maintainers fix it here, you can try my fork. 

I'm even gonna try and update it so that it can work with more updated versions of python and networkx. Stay tuned!

**Comment by chelseashuu** [comment]
I tried writing .pdb after the name of the ligand in the .mol2 file and it worked! Seems like a semantics issue

**Comment by GuangYang007** [comment]
> I tried writing .pdb after the name of the ligand in the .mol2 file and it worked! Seems like a semantics issue

Hi, I have the same problem. But I don't get what you mean by "writing .pdb after the name of the ligand in the .mol2 file". Could you explain specifically where should I put the ".pdb"? Thank you.
